# Generated by Django 5.1.1 on 2024-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Package_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("in_transit", "In Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
